artist/urls.py
from django.conf.urls import include, patterns, url


view_location = 'customProfile.views'
urlpatterns = patterns(view_location,
    # Views
    url(r'^(?P<username>[-\w]+)/', include(patterns(view_location,
        url(r'^$', 'profileRedirect', {'redirect_url': 'artist:about'}, name='home'),
        url(r'^news/$', 'artist_news', name='news'),
        url(r'^shows/$','shows', name='shows'),
        url(r'^shows/(?P<year>\d{4})/$','shows',name='shows'),
        url(r'^photos/$', 'artist_photos', name='photos'),
    ))),
)

view_location = 'social_links.views'
urlpatterns += patterns(view_location,
    # Forms
    url(r'^about/links/edit/$', 'artist_social_links', name='socialLinksForm'),
    url(r'^photos/links/edit/$', 'artist_photo_links', name='photoLinksForm'),
    url(r'^music/links/edit/$', 'music_links', name='musicLinksForm'),
    url(r'^videos/links/edit/$', 'artist_video_links', name='videoLinksForm'),
)

view_location = 'artist.views'
urlpatterns += patterns(view_location,
    # Views
    url(r'^(?P<username>[-\w]+)/', include(patterns(view_location,
        url(r'^about/$', 'about', name='about'),
        url(r'^music/$', 'music', name='music'),
        url(r'^videos/$', 'videos', name='videos'),
    ))),

    #Forms
    url(r'^about/', include(patterns(view_location,
        url(r'^biography/edit/$', 'biography', name='biographyForm'),
        url(r'^contact/edit/$', 'contact_info', name='userContactForm'),
        url(r'^member/add/$', 'members', name='memberForm'),
        url(r'^member/edit/(?P<member_id>[\.\w-]+)$', 'members', name='memberForm'),
        url(r'^(?P<contact_type>[\.\w-]+)/edit/$', 'contacts', name='contactForm'),
    ))),
    url(r'^music/', include(patterns(view_location,
        url(r'^album/add/$', 'AddEditAlbum', name='albumForm'),
        url(r'^album/(?P<album_id>[\.\w-]+)/edit/$', 'AddEditAlbum', name='editAlbumForm'),
        url(r'^album/(?P<album_id>[\.\w-]+)/tracks/add/$', 'AddEditTracks', name='tracksForm'),
        #url(r'^interview/add/$', 'interview_form', name='interview_form'),
        #url(r'^interview/add/(?P<trackID>[\.\w-]+)$', 'interview_form', name='interview_form'),
    ))),
    url(r'^videos/', include(patterns(view_location,
        url(r'^add/$', 'video_form', name='video_form'),
        url(r'^album/add/$', 'AddEditAlbum', {'success_url': 'artist:video_tracks_form'}, name='video_album_form'),
        url(r'^album/(?P<album_id>[\.\w-]+)/edit/$', 'AddEditAlbum', {'success_url': 'artist:video_tracks_form'}, name='video_edit_album'),
        url(r'^album/(?P<album_id>[\.\w-]+)/tracks/add/$', 'add_video_to_album', name='video_tracks_form'),
        #url(r'^interview-video/add/$', 'interview_video_form', name='interview_video_form'),
        #url(r'^interview-video/add/(?P<trackID>[\.\w-]+)$', 'interview_video_form', name='interview_video_form'),
    ))),
)

fan/urls.py
from django.conf.urls import include, patterns, url


view_location = 'customProfile.views'
urlpatterns = patterns(view_location,
    # Views
    url(r'^(?P<username>[-\w]+)/', include(patterns(view_location,
        url(r'^$', 'profileRedirect', {'redirect_url': 'fan:news'}, name='home'),
        url(r'^news/$', 'fan_news', name='news'),
        url(r'^photos/$', 'fan_photos', name='photos'),
    ))),
)

view_location = 'fan.views'
urlpatterns += patterns(view_location,
    url(r'^(?P<username>[-\w]+)/', include(patterns(view_location,
        url(r'^about/$', 'about', name='about'),
    ))),

)

threads/urls.py
from django.conf.urls import patterns
from django.conf.urls import url


urlpatterns = patterns('threads.views',
    url(r'^$', 'inbox', name='inbox'),
    url(r'^sent/$', 'sent', name='sent'),
    url(r'^trash/$', 'trash', name='trash'),
    url(r'^compose/$', 'compose', name='compose'),
    url(r'^compose/(?P<recipient>[\+\w]+)/$', 'compose', name='compose'),
    url(r'^view/(?P<thread_id>[\d]+)/$', 'view', name='detail'),
    url(r'^batch-update/$', 'batch_update', name='batch_update'),
    url(r'^message-reply/(?P<thread_id>[\d]+)/$', 'message_ajax_reply', name="reply"),

)

userena/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views

from userena import settings as userena_settings
from userena.compat import auth_views_compat_quirks, password_reset_uid_kwarg


def merged_dict(dict_a, dict_b):
    """Merges two dicts and returns output. It's purpose is to ease use of
    ``auth_views_compat_quirks``
    """
    dict_a.update(dict_b)
    return dict_a

urlpatterns = patterns('userena.views',
    # Signup, signin and signout
    url(r'^signout/$', 'signout', name='signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       merged_dict({'template_name': 'accounts/password_reset_form.html',
                    'email_template_name': 'accounts/email_password_reset_message.txt',
                    'extra_context': {'without_usernames': userena_settings.USERENA_WITHOUT_USERNAMES}
                   }, auth_views_compat_quirks['userena_password_reset']),
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'accounts/password_reset_done.html',},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<%s>[0-9A-Za-z]+)-(?P<token>.+)/$' % password_reset_uid_kwarg,
       auth_views.password_reset_confirm,
       merged_dict({'template_name': 'accounts/password_reset_confirm_form.html',
                    }, auth_views_compat_quirks['userena_password_reset_confirm']),
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'accounts/password_reset_complete.html'},
        name='userena_password_reset_complete'),


    # Change password
    #url(r'^(?P<username>[\.\w-]+)/password/$', 'password_change', name='password_change'),
    #url(r'^(?P<username>[\.\w-]+)/password/complete/$',
    #   'direct_to_user_template',
    #   {'template_name': 'accounts/password_complete.html'},
    #   name='password_change_complete'),

)

tracks/models.py
import os
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext as _

from .utils import json_playlist
from audiofield.fields import AudioField
from embed_video.fields import EmbedVideoField
from genres.models import Genre
from photos.models import Image


def get_audio_upload_path(instance, filename):
    if hasattr(instance, 'upload_to_info'):
        username, track_type, album_title = instance.upload_to_info
        if album_title:
            return os.path.join(username, track_type, album_title, filename)
        else:
            return os.path.join(username, track_type, filename)
    else:
        return os.path.join(instance.title, filename)

class Album(models.Model):
    artist_profile = models.ForeignKey('artist.ArtistProfile',
                          related_name='albums',null=True,
                          blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    album_art = models.ForeignKey(Image,
                          related_name='artist_album_art',null=True,
                          blank=True, on_delete=models.SET_NULL)
    title = models.CharField(_('Title'), max_length=100)
    genre = models.ManyToManyField(Genre, verbose_name=_("genre"),
                                   related_name='album_genre',
                                   blank=True)
    year = models.CharField(_("Year"), max_length="4", null=True,
                            blank=True)
    description = models.TextField(_("Description"), null=True,
                                   blank=True)

    def __unicode__(self):
        return '%s'% self.id

    def get_json_playlist(self):
        if not hasattr(self, '_cached_playlist'):
            self._cached_playlist = json_playlist(self.track_set.all(), self)
        return self._cached_playlist

def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.mp3','.oga']
    if not ext in valid_extensions:
        raise ValidationError(u'File type not supported')

class Track(models.Model):
    album = models.ForeignKey(Album, related_name='track_set')
    title = models.CharField(_('Title'), max_length=128, default="untitled")
    video = EmbedVideoField(_('Video Link'), null=True, blank=True,
                            help_text="Link to youtube or vimeo")
    audio = AudioField(_("Audio file"), upload_to=get_audio_upload_path,
                       ext_whitelist=('.mp3','.ogg'),
                       help_text="Currently supports mp3 and ogg",
                       null=True, blank=True)
    order = models.PositiveSmallIntegerField(verbose_name=_("order"))

    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return '%s'% self.id

    def set_upload_to_info(self, username, track_type, album_title=None):
        """
            username = username of who saving the model
            track_type = albums/covers/interviews
            album_title = if album whats its title
        """
        self.upload_to_info = (username, track_type, album_title)


class Video(models.Model):
    user = models.ForeignKey(User, related_name='videos')
    video = EmbedVideoField(_('Video Link'), help_text="Link to youtube or vimeo")

artist/views/about.py
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.views.generic import UpdateView

from accounts.utils import update_profile_weight
from artist.models import ArtistProfile
from annoying.functions import get_object_or_None
from contact.views import ContactView
from contact.forms import NonUserLocationForm
from customProfile.views import ArtistProfileView, ArtistProfileFormMixin
from artist.models import Member
from artist.forms import BiographyForm, MemberForm


class AboutView(ArtistProfileView):
    template_name = 'artist/about.html'

    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context['members'] = context['artist_profile'].members.filter(
            current_member=True
        )
        return context

about = AboutView.as_view()

class BiographyView(ArtistProfileFormMixin, UpdateView):
    form_class = BiographyForm
    template_name = 'artist/forms/biography.html'
    model = ArtistProfile
    success_url = 'artist:about'

    def get_object(self, queryset=None):
        return self.user.profile.artist_profile

    def get_success_url(self):
        update_profile_weight(user=self.user)
        return reverse(self.success_url, kwargs={'username': self.user.username})

biography = BiographyView.as_view()

class ContactInfoView(ArtistProfileFormMixin, ContactView):
    success_url = 'artist:about'
    template_name = 'artist/forms/contact.html'

    def get_context_data(self, **kwargs):
        context = super(ContactInfoView, self).get_context_data(**kwargs)
        context['contact_type'] = 'band'
        return context

contact_info = ContactInfoView.as_view()

class MemberView(ArtistProfileFormMixin, UpdateView):
    form_class = MemberForm
    model = Member
    member_id=None
    template_name = 'artist/forms/member.html'
    success_url = 'artist:about'

    def dispatch(self, *args, **kwargs):
        member_id = self.kwargs.get('member_id', None)
        self.member = get_object_or_None(self.model, id=member_id)
        return super(MemberView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MemberView, self).get_context_data(**kwargs)
        members = self.user.profile.artist_profile.members
        context['members'] = members.filter(current_member=True).order_by('name')
        context['past_members'] = members.filter(current_member=False).order_by('name')
        context['member'] = self.member
        return context

    def get_object(self, queryset=None):
        return self.member

    def form_valid(self, form):
        form.save(artist=self.user.profile.artist_profile)
        return redirect(self.success_url, username=self.user.username)

members = MemberView.as_view()

class MusicianContactsView(ArtistProfileFormMixin, ContactView):
    locationForm = NonUserLocationForm
    template_name = 'artist/forms/contact.html'
    success_url = 'artist:about'
    contact_type = None
    CONTACT_TYPES = {
        'booking':'booking_contact',
        'label':'label_contact',
        'management':'management_contact',
        'press':'press_contact',
    }

    def dispatch(self, *args, **kwargs):
        if not self.contact_type:
            self.contact_type = self.kwargs.get('contact_type', None)
        if self.contact_type not in self.CONTACT_TYPES:
            self.contact_type = self.CONTACT_TYPES.keys()[0]
        return super(MusicianContactsView, self).dispatch(*args, **kwargs)

    def get_contact_info(self):
        return getattr(self.user.profile.artist_profile, self.CONTACT_TYPES[self.contact_type])

    def set_contact_info(self, contact_info):
        setattr(self.user.profile.artist_profile, self.CONTACT_TYPES[self.contact_type],contact_info)
        self.user.profile.artist_profile.save()
        return contact_info

    def get_context_data(self, **kwargs):
        context = super(MusicianContactsView, self).get_context_data(**kwargs)
        context['contact_type'] = self.contact_type
        return context

contacts = MusicianContactsView.as_view()

artist/views/music.py
from django.conf import settings
from django.forms.models import inlineformset_factory
from django.shortcuts import render, redirect
from django.views.generic import UpdateView

from annoying.functions import get_object_or_None
from annoying.views import MultipleModelFormsView
from customProfile.views import ArtistProfileView, ArtistProfileFormMixin
from photos.models import Image
from photos.forms import AlbumArtForm
from photos.views import ImageFormMixin
from tracks.forms import AlbumForm, AlbumAudioForm, TracksForm
from tracks.models import Album, Track


class MusicView(ArtistProfileView):
    template_name = 'artist/music.html'

music = MusicView.as_view()

class AlbumView(ArtistProfileFormMixin, ImageFormMixin, MultipleModelFormsView):
    form_classes = {
      'albumForm' : AlbumForm,
      'albumArtForm' : AlbumArtForm
    }
    album_id=None
    template_name = 'artist/forms/album.html'
    success_url = 'artist:tracksForm'

    def get_objects(self, queryset=None):
        self.album_id = self.kwargs.get('album_id', None)
        album = get_object_or_None(Album, id=self.album_id)
        return {
          'albumForm' : album,
          'albumArtForm' : album.album_art if album else None
        }

    def forms_valid(self, forms):
        album = forms['albumForm'].save(request=self.request, commit=False)
        album.artist_profile = self.request.user.profile.artist_profile
        if self.request.FILES.get('image'):
            album.album_art = Image.objects.create(
                image=self.request.FILES.get('image'),
                title = album.title,
                user = self.request.user
            )
        elif self.request.POST.get('album_art'):
            imageId = self.request.POST.get('album_art')
            album.album_art = get_object_or_None(Image, id=imageId)
        album.save()
        forms['albumForm'].save(request=self.request)
        forms['albumForm'].save_m2m()
        return redirect(self.success_url, album_id=album.id)

AddEditAlbum = AlbumView.as_view()

class TracksView(ArtistProfileFormMixin, UpdateView):
    form_class = AlbumAudioForm
    model = Album
    inline_model = Track
    object = None
    album_id = None
    template_name = 'artist/forms/track.html'
    success_url = 'artist:music'

    def get_object(self, queryset=None):
        self.album_id = self.kwargs.get('album_id', None)
        album = get_object_or_None(self.model, id=self.album_id)
        self.object = album
        return album

    def get_formset(self):
        inline_formset = inlineformset_factory(self.model,
                                               self.inline_model,
                                               form=self.form_class,)
        form_kwargs = self.get_form_kwargs()
        formset = inline_formset(**form_kwargs)
        return formset

    def get_context_data(self):
        self.get_object()
        formset = self.get_formset()
        tracks = Track.objects.filter(album=self.album_id)
        formset_tracks = zip(formset, tracks)
        context = {
            'formset'        : formset,
            'formset_tracks' : formset_tracks,
            'tracks_form'    : TracksForm(**self.get_form_kwargs()),
            'media_url'      : settings.MEDIA_URL,
        }
        return context

    def get(self, request, **kwargs):
        return render(request, self.template_name, self.get_context_data())

    def post(self, request, **kwargs):
        context = self.get_context_data()
        if context['formset'].is_valid():
            for form in context['formset']:
                cleaned_data = form.cleaned_data
                if cleaned_data:
                    track = cleaned_data['id']
                    track.title = cleaned_data['title']
                    track.save()
                    form.save()
            if request.FILES.getlist('tracks'):
                context['tracks_form'].save(request=self.request)
                return redirect(request.path_info)
            else:
                return redirect(self.success_url, username=self.user.username)
        return render(request, self.template_name, context)

AddEditTracks = TracksView.as_view()

composersCouch/templates/artist/forms/about_modal.html
{% extends 'utils/formModal.html' %}

{% block modalNav %}
  <ul class="nav nav-pills">
    <li class="{% block biographyClass %}{% endblock %}">
      <a class="editMusicianBiography" href="{{ url('artist:biographyForm') }}">Biography</a>
    </li>
    <li class="{% block memberClass %}{% endblock %}">
      <a class="editMusicianMembers" href="{{ url('artist:memberForm') }}">Members</a>
    </li>
    <li class="{% block contactClass %}{% endblock %}">
      <a class="editMusicianContact" href="{{ url('artist:userContactForm') }}">Contact</a>
    </li>
  </ul>
{% endblock %}

composersCouch/templates/artist/forms/album.html
{% extends 'utils/form.html' %}
{% from "utils/macros.html" import image_select %}
{% from "utils/form_macros.html" import non_field_errors, field %}


{% block title %}
  {% block formTitle %}Add Album{% endblock %}
{% endblock %}

{% block formID %}album-form{% endblock %}
{% block enctype %}multipart/form-data{% endblock %}

{% block form %}
    {{ render_form(albumArtForm) }}
    {% if images %}
      {{ image_select(request=request, images=images, id="album_art", label="Album Art") }}
    {% endif %}
    <script>
      {# variables for image select #}
      var selectorId = "#id_album_art";
      var selectDiv  = "#div_id_album_art";
      var uploadDiv  = "#div_id_image";
      {% if images %}
        var images = true;
      {% else %}
        var images = false;
      {% endif %}
    </script>
    {{ non_field_errors(albumForm) }}
    <div class="row no-gutter">
      <div class="col-sm-6 left">{{ field(albumForm.title) }}</div>
      <div class="col-sm-6 right">{{ field(albumForm.year) }}</div>
    </div>
    {{ field(albumForm.genre) }}
    {{ field(albumForm.description) }}
{% endblock %}

{% block extraSubmit %}
  {{ progress_bar() }}
{% endblock %}

composersCouch/templates/artist/forms/biography.html
{% extends 'artist/forms/about_modal.html' %}


{% block title %}Edit Biography{% endblock %}

{% block biographyClass %}active{% endblock %}

{% block formID %}biographyMusicianForm{% endblock %}

{% block formTitle %}Edit Biography{% endblock %}

{% block form %}
  {{ render_form(form) }}
{% endblock %}

composersCouch/templates/artist/forms/contact.html
{% extends 'artist/forms/about_modal.html' %}
{% from "profile/macros.html" import contact_form, location_form %}


{% block contactClass %}active{% endblock %}

{% block title %}{% block formTitle %}{{ contact_type|title }} Contact Info{% endblock %}{% endblock %}
{% block formID %}contactMusicianForm{% endblock %}
{% block form %}
  <span>Edit: </span>
  <a class="editMusicianContact {% if contact_type == 'band' %}text-bold{% endif %}" href="{{ url('artist:userContactForm') }}">Band</a>,
  <a class="editMusicianContact {% if contact_type == 'booking' %}text-bold{% endif %}" href="{{ url('artist:contactForm', kwargs={'contact_type':'booking'}) }}">Booking</a>,
  <a class="editMusicianContact {% if contact_type == 'label' %}text-bold{% endif %}" href="{{ url('artist:contactForm', kwargs={'contact_type':'label'}) }}">Label</a>,
  <a class="editMusicianContact {% if contact_type == 'management' %}text-bold{% endif %}" href="{{ url('artist:contactForm', kwargs={'contact_type':'management'}) }}">Management</a>,
  <a class="editMusicianContact {% if contact_type == 'press' %}text-bold{% endif %}" href="{{ url('artist:contactForm', kwargs={'contact_type':'press'}) }}">Press</a>
  {{ contact_form(contactForm) }}
  {{ location_form(locationForm) }}
{% endblock %}

composersCouch/templates/artist/forms/member.html
{% extends 'artist/forms/about_modal.html' %}



{% block title %}
  {% block formTitle %}
    Edit Member
  {% endblock %}
{% endblock %}

{% block memberClass %}active{% endblock %}

{% block formID %}membersMusicianForm{% endblock %}

{% block form %}
  <div>
    {% if members %}
      <span>Edit members: </span>
      {% for m in members %}
        <a class="{% if m == member %}text-bold{% endif %} editMusicianMembers" href="{{ url('artist:memberForm', kwargs={'member_id':m.id}) }}">
          {{m.name}},
        </a>
      {% endfor %}
      <span>or </span>
      <a class="editMusicianMembers text-success" href="{{ url('artist:memberForm') }}">
        Add New
      </a>
    {% endif %}
  </div>
  <div class="text-muted">
    {% if past_members %}
      <span>Edit past members: </span>
      {% for m in past_members %}
        <a class="{% if m == member %}text-bold{% endif %} editMusicianMembers" href="{{ url('artist:memberForm', kwargs={'member_id':m.id}) }}">
          {{m.name}}{% if not loop.last %},{% endif %}
        </a>
      {% endfor %}
    {% endif %}
  </div>
  {{ render_form(form) }}
{% endblock %}

composersCouch/templates/artist/forms/track.html
{% extends 'utils/form.html' %}
{% from "utils/form_macros.html" import non_field_errors, field %}


{% block title %}{% block formTitle %}Add Tracks{% endblock %}{% endblock %}

{% block formID %}tracks-form{% endblock %}
{% block enctype %}multipart/form-data{% endblock %}
{% block form %}
  {% if messages %}
    <div class="alert alert-danger">
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
  {{ formset.management_form }}
  {% for form,track in formset_tracks %}
    <div class="track-formset">
      {{ non_field_errors(form) }}
      {{ field(form.id) }}
      <div class="hidden">{{ field(form.album) }}</div>
      <div class="row audio-layout no-gutter">
        <div class="col-sm-2 left">{{ field(form.order) }}</div>
        <div class="col-sm-9 center">{{ field(form.title) }}</div>
        <div class="col-sm-1 right">
          <label>Remove</label>
          <div class="pull-right">
            {{ field(form.DELETE, hide_label=True) }}
          </div>
        </div>
        <label>Currently</label>
        <audio controls>
          <source src='{{media_url}}{{track.audio}}' type='audio/mp3'>
            Your browser does not support the audio element.
        </audio>
      </div>
    </div>
  {% endfor %}
  {{ render_form(tracks_form) }}

{% endblock %}

{% block extraSubmit %}{{ progress_bar() }}{% endblock %}

composersCouch/templates/artist/forms/track_video.html
{% extends 'utils/form.html' %}
{% from "utils/form_macros.html" import non_field_errors, field %}


{% block title %}
  {% block formTitle %}Add Tracks{% endblock %}
{% endblock %}

{% block formID %}tracks-form{% endblock %}

{% block form %}
  {{ formset.management_form }}
  {% for form in formset %}
    {{ non_field_errors(form) }}
    {{ field(form.id) }}
    <div class="hidden">{{ field(form.album) }}</div>
    <div class="row audio-layout no-gutter">
      <div class="col-sm-2 left">{{ field(form.order) }}</div>
      <div class="col-sm-5 center">{{ field(form.title) }}</div>
      <div class="col-sm-5 right">{{ field(form.video) }}</div>
    </div>
  {% endfor %}
{% endblock %}

composersCouch/templates/artist/forms/videos.html
{% extends 'utils/form.html' %}
{% from "utils/form_macros.html" import non_field_errors, field %}


{% block title %}
  {% block formTitle %}Add Tracks{% endblock %}
{% endblock %}

{% block formID %}tracks-form{% endblock %}

{% block form %}
  {{ form.management_form }}
  {% for f in form %}
    {{ non_field_errors(f) }}
    {{ field(f.id) }}
    {{ field(f.video) }}
  {% endfor %}
{% endblock %}